name: ${name}
main: com.github.maxopoly.artemis.ArtemisPlugin
version: ${version}
authors:
  - Maxopoly
  - Diet_Cola
  - xFier
depend:
  - CivModCore
  - CombatTagPlus
api-version: 1.17
permissions:
    artemis.tp:
      description: Gives access to the teleport command
      default: op
